name: Feature request
description: Propose behavior for future consideration
title: ""
labels:
  - type:feature
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
    validations:
      required: true
  - type: textarea
    id: behavior
    attributes:
      label: Proposed behavior
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Scope
    validations:
      required: true
  - type: textarea
    id: implications
    attributes:
      label: Networking or privilege implications
    validations:
      required: true
